### PR TITLE
Weasis codec dcm4che14 support

### PR DESCRIPTION
**Pull request by mischwarz**
Changes to get weasis-codec working with dcm4che14/dcm4chee 2.18.3 on windows 64bit
 - Java 7
 - StreamAdaptor for SegmentedImageInputStream with mapper of type org.dcm4cheri.image.ItemParser
 - ColorModel of ImageReadParam.getDestination to apply WL/WW to WADO
 - fix error with wrong Buffersize for JPEG-LS

This enables usage outside of weasis and - as far as I can see - there is no impact on rest of weasis codebase. Would be nice to see this upstream. Looking forward to hear your comments on this!

### CODE REVIEW

**Comment by mischwarz** [comment]
Looking forward for the 2.5.0 release. Evaluating a way to include my changes later would be great.
This commit [fix size of OutputBuffer by using numberOfBytes](https://github.com/nroduit/Weasis/pull/11/commits/1c66089808fe6c5a0eb40a9253ebb4cbb2f00f1b) is a bug fix for the JPEG LS Writer.

Remarks: I have found NativeJPEGImageReader to be unstable in dcm4chee 2.18.3 due to a EXCEPTION_ACCESS_VIOLATION in stability test running several hours (Error occured in org.weasis.jpeg.cpp.libijg$DJDecompressIJG12/16Bit.decode).

Procedure to patch dcm4chee 2.18.3 to use weasis-codec: 
1. Add ImageReaderFactory-win64bit.properties e.g. in bin folder
[ImageReaderFactory-win64bit.properties.txt](https://github.com/nroduit/Weasis/files/575109/ImageReaderFactory-win64bit.properties.txt)
2. Add ImageWriterFactory-win64bit.properties e.g. in bin folder
[ImageWriterFactory-win64bit.properties.txt](https://github.com/nroduit/Weasis/files/575110/ImageWriterFactory-win64bit.properties.txt)
3. Add to JAVA_OPTS in run.bat:
`set JAVA_OPTS=%JAVA_OPTS% -Dorg.dcm4cheri.image.ImageReaderFactory=file:///%JBOSS_HOME%/bin/ImageReaderFactory-win64bit.properties
set JAVA_OPTS=%JAVA_OPTS% -Dorg.dcm4cheri.image.ImageWriterFactory=file:///%JBOSS_HOME%/bin/ImageWriterFactory-win64bit.properties
`
4. Put 64bit jnilibijg.dll and jniopenjpeg.dll to bin/native folder + remove 32bit clib_*.dll
5. Place theses jars in server/default/lib:
  weasis-image-jni-2.5.0-SNAPSHOT.jar
  weasis-image-jpeg-codec-2.5.0-SNAPSHOT.jar
  weasis-image-openjpeg-codec-2.5.0-SNAPSHOT.jar
6. Replace jai_imageio.jar with this one https://github.com/nroduit/mvn-repo/blob/master/org/weasis/thirdparty/com/sun/media/jai_imageio/1.2.4/jai_imageio-1.2.4.jar (but leave filename as jai_imageio.jar with out version)

**Comment by nroduit** [comment]
> Looking forward for the 2.5.0 release. Evaluating a way to include my changes later would be great.

Yes the best way would be to make another project to build the necessary packages for patching dcm4chee-2.18.3.

> This commit fix size of OutputBuffer by using numberOfBytes is a bug fix for the JPEG LS Writer.

This size is divided by 2 because the buffer of the compressed data won't be larger than a factor 2 of the raw data. This is for saving time and memory during the process.

> Remarks: I have found NativeJPEGImageReader to be unstable in dcm4chee 2.18.3 due to a EXCEPTION_ACCESS_VIOLATION in stability test running several hours (Error occured in org.weasis.jpeg.cpp.libijg$DJDecompressIJG12/16Bit.decode).

Did you try with a recent version? If you manage to reproduce the issue, please let me know how.

**Comment by mischwarz** [comment]
>> This commit fix size of OutputBuffer by using numberOfBytes is a bug fix for the JPEG LS Writer.

>This size is divided by 2 because the buffer of the compressed data won't be larger than a factor 2 of the >raw data. This is for saving time and memory during the process.

When I tried to compress the RG1_UNC of the clunie compsamples_ref, I received error "Compressed Buffer Too Small". So I think worst case for compression is that size remains the same. At least a factor 2 is not guaranted.

>> Remarks: I have found NativeJPEGImageReader to be unstable in dcm4chee 2.18.3 due to a 
>> EXCEPTION_ACCESS_VIOLATION in stability test running several hours (Error occured in 
>> org.weasis.jpeg.cpp.libijg$DJDecompressIJG12/16Bit.decode).

> Did you try with a recent version? If you manage to reproduce the issue, please let me know how.

The error occured not deterministicly but was reproducable. 
1. Send CT1_JPLL of clunie compsamples to archive
2. disable wado cache to force decompression for each wado request
3. use dcmwado to send multiple parallel request for CT1_JPLL in endless loop to simulate constant (not peak) load.
After a few hours the archive crashed with the mentioned error. The archive runs stable for same test with JPEGLS/JPEG2000. That's why I think the problem is somewhere with NativeJPEGImageReader. 

Unfortunately it was not reproducible in a simple test program running a endless loop of direct calls to decrompress the given CT1_JPLL - neither sequential nor in concurrent exceution. Only when integrated in dcm4chee. Seems to be a tricky one. Perhaps you have any further ideas to narrow down the source of the problem.

**Comment by nroduit** [comment]
I partially report your modifications in this [commit](https://github.com/nroduit/Weasis/commit/d629d8cb3bbe0241f4f6aa23c424346056e85cd8).

In weasis-imageio-codec the registration is made in the activator to ensure an unique registration with the right classloader with OSGI registration (not SPI service).
In weasis the native libraries are manage through OSGI using bundle fragments and simply the label associated to the system and the processor architecture (see http://www.osgi.org/Specifications/Reference and the [weasis implementation](https://github.com/nroduit/Weasis/blob/master/weasis-launcher/src/main/java/org/weasis/launcher/WeasisLauncher.java) in setSystemSpecification()).

So I think the best option would be to create a new project to package the codecs for any platforms and then simply extract in dcm4chee 2.18. It should something similar to what I've done for the [dcm4che3 toolkit](https://github.com/nroduit/dcm4che/tree/dcm4chee-arc-light/dcm4che-imageio-codec)

Could you send me the crash report file of EXCEPTION_ACCESS_VIOLATION. It could help to locate where is the problem (I guess in C++ part).

**Comment by mischwarz** [comment]
Thanks for taking into account my suggestions. Now the weasis-codec can be used in a separate project as you suggested. I will notify when I find time to create such a project.

Here the crash report:
[hs_err_pid10324.log.txt](https://github.com/nroduit/Weasis/files/636726/hs_err_pid10324.log.txt)

**Comment by nroduit** [comment]
This request is no longer relevant. See recent dcm4che integration https://github.com/dcm4che/dcm4chee-arc-light/issues/1292

**Pull request closed without merging**
